version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./docker_db:/var/lib/postgresql/data

  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
    tty: true
