default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") %>
  user: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: space_flight_news_database

test:
  <<: *default
  database: space_flight_news_test

production:
  <<: *default
  database: space_flight_news_production
  username: space_flight_news
  password: <%= ENV['SPACE_FLIGHT_NEWS_DATABASE_PASSWORD'] %>
